/* tslint:disable */
/* eslint-disable */
/**
 * 🧺 Washify API Documentation
 * API documentation for Washify - Laundry Management System  Hầu hết APIs yêu cầu JWT token. Sử dụng endpoint /api/auth/login để lấy token.  **API Groups:** - Customer API: Endpoints cho khách hàng (đặt hàng, thanh toán, review) - Admin API: Endpoints cho quản lý (ADMIN, MANAGER, STAFF) - Shipper API: Endpoints cho shipper (giao hàng) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@washify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

