/* tslint:disable */
/* eslint-disable */
/**
 * 🧺 Washify API Documentation
 * API documentation for Washify - Laundry Management System  Hầu hết APIs yêu cầu JWT token. Sử dụng endpoint /api/auth/login để lấy token.  **API Groups:** - Customer API: Endpoints cho khách hàng (đặt hàng, thanh toán, review) - Admin API: Endpoints cho quản lý (ADMIN, MANAGER, STAFF) - Shipper API: Endpoints cho shipper (giao hàng) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@washify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ApiResponseBoolean {
    'success'?: boolean;
    'message'?: string;
    'data'?: boolean;
    'timestamp'?: string;
}
export interface ApiResponseListNotificationResponse {
    'success'?: boolean;
    'message'?: string;
    'data'?: Array<NotificationResponse>;
    'timestamp'?: string;
}
export interface ApiResponseLong {
    'success'?: boolean;
    'message'?: string;
    'data'?: number;
    'timestamp'?: string;
}
export interface ApiResponseMapStringObject {
    'success'?: boolean;
    'message'?: string;
    'data'?: { [key: string]: object; };
    'timestamp'?: string;
}
export interface ApiResponseNotificationResponse {
    'success'?: boolean;
    'message'?: string;
    'data'?: NotificationResponse;
    'timestamp'?: string;
}
export interface ApiResponsePageNotificationResponse {
    'success'?: boolean;
    'message'?: string;
    'data'?: PageNotificationResponse;
    'timestamp'?: string;
}
export interface ApiResponseVoid {
    'success'?: boolean;
    'message'?: string;
    'data'?: object;
    'timestamp'?: string;
}
export interface ForgotPasswordRequest {
    'email': string;
}
export interface NotificationRequest {
    'userId': number;
    'title': string;
    'message': string;
    'type': NotificationRequestTypeEnum;
    'relatedId'?: number;
}

export const NotificationRequestTypeEnum = {
    OrderCreated: 'ORDER_CREATED',
    OrderConfirmed: 'ORDER_CONFIRMED',
    OrderProcessing: 'ORDER_PROCESSING',
    OrderReady: 'ORDER_READY',
    OrderDelivering: 'ORDER_DELIVERING',
    OrderCompleted: 'ORDER_COMPLETED',
    OrderCancelled: 'ORDER_CANCELLED',
    PaymentSuccess: 'PAYMENT_SUCCESS',
    PaymentFailed: 'PAYMENT_FAILED',
    Promotion: 'PROMOTION',
    System: 'SYSTEM',
    Other: 'OTHER'
} as const;

export type NotificationRequestTypeEnum = typeof NotificationRequestTypeEnum[keyof typeof NotificationRequestTypeEnum];

export interface NotificationResponse {
    'id'?: number;
    'userId'?: number;
    'username'?: string;
    'title'?: string;
    'message'?: string;
    'type'?: string;
    'relatedId'?: number;
    'isRead'?: boolean;
    'readAt'?: string;
    'createdAt'?: string;
}
export interface PageNotificationResponse {
    'totalElements'?: number;
    'totalPages'?: number;
    'size'?: number;
    'content'?: Array<NotificationResponse>;
    'number'?: number;
    'sort'?: Array<SortObject>;
    'first'?: boolean;
    'last'?: boolean;
    'numberOfElements'?: number;
    'pageable'?: PageableObject;
    'empty'?: boolean;
}
export interface PageableObject {
    'offset'?: number;
    'sort'?: Array<SortObject>;
    'unpaged'?: boolean;
    'paged'?: boolean;
    'pageSize'?: number;
    'pageNumber'?: number;
}
export interface ResetPasswordRequest {
    'token': string;
    'newPassword': string;
    'confirmPassword': string;
}
export interface SortObject {
    'direction'?: string;
    'nullHandling'?: string;
    'ascending'?: boolean;
    'property'?: string;
    'ignoreCase'?: boolean;
}

/**
 * EmailVerificationApi - axios parameter creator
 */
export const EmailVerificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Check đầy đủ bao gồm SMTP verification. Chậm, dùng cẩn thận!
         * @summary Xác thực email sâu (SMTP)
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deepVerify: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('deepVerify', 'email', email)
            const localVarPath = `/api/auth/email/verify-deep`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Xác thực email đầy đủ: Format + Disposable + MX records.  **3 Levels Check:** 1. ✅ Format validation (RFC 5322) 2. ✅ Disposable email check (block tempmail) 3. ✅ MX records check (domain có thể nhận email)  **Speed:** 50-200ms (DNS query)  **Use Case:** - Verify email trước khi register - Ensure email có thể nhận mail - Block fake domains  **Examples:** - ✅ test@gmail.com → Valid (has MX records) - ❌ test@tempmail.com → Invalid (disposable) - ❌ test@fakefake123.com → Invalid (no MX records)  **Response:** ```json {   \"email\": \"test@gmail.com\",   \"validFormat\": true,   \"isDisposable\": false,   \"hasMXRecords\": true,   \"mxRecords\": [\"gmail-smtp-in.l.google.com\"],   \"isValid\": true,   \"reason\": \"Email hợp lệ và có thể nhận email\" } ``` 
         * @summary 🌐 Full email verification
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fullVerify: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('fullVerify', 'email', email)
            const localVarPath = `/api/auth/email/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Kiểm tra nhanh email format và disposable email.  **Checks:** - ✅ Format validation (RFC 5322) - ✅ Disposable email check (tempmail, guerrillamail, etc.)  **Speed:** < 1ms (very fast)  **Use Case:** - Frontend real-time validation - Check email trước khi đăng ký - Block disposable emails  **Response:** ```json {   \"email\": \"test@gmail.com\",   \"validFormat\": true,   \"isDisposable\": false,   \"isValid\": true } ``` 
         * @summary 🌐 Quick check email
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quickCheck: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('quickCheck', 'email', email)
            const localVarPath = `/api/auth/email/check`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmailVerificationApi - functional programming interface
 */
export const EmailVerificationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmailVerificationApiAxiosParamCreator(configuration)
    return {
        /**
         * Check đầy đủ bao gồm SMTP verification. Chậm, dùng cẩn thận!
         * @summary Xác thực email sâu (SMTP)
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deepVerify(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseMapStringObject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deepVerify(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailVerificationApi.deepVerify']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Xác thực email đầy đủ: Format + Disposable + MX records.  **3 Levels Check:** 1. ✅ Format validation (RFC 5322) 2. ✅ Disposable email check (block tempmail) 3. ✅ MX records check (domain có thể nhận email)  **Speed:** 50-200ms (DNS query)  **Use Case:** - Verify email trước khi register - Ensure email có thể nhận mail - Block fake domains  **Examples:** - ✅ test@gmail.com → Valid (has MX records) - ❌ test@tempmail.com → Invalid (disposable) - ❌ test@fakefake123.com → Invalid (no MX records)  **Response:** ```json {   \"email\": \"test@gmail.com\",   \"validFormat\": true,   \"isDisposable\": false,   \"hasMXRecords\": true,   \"mxRecords\": [\"gmail-smtp-in.l.google.com\"],   \"isValid\": true,   \"reason\": \"Email hợp lệ và có thể nhận email\" } ``` 
         * @summary 🌐 Full email verification
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fullVerify(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseMapStringObject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fullVerify(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailVerificationApi.fullVerify']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Kiểm tra nhanh email format và disposable email.  **Checks:** - ✅ Format validation (RFC 5322) - ✅ Disposable email check (tempmail, guerrillamail, etc.)  **Speed:** < 1ms (very fast)  **Use Case:** - Frontend real-time validation - Check email trước khi đăng ký - Block disposable emails  **Response:** ```json {   \"email\": \"test@gmail.com\",   \"validFormat\": true,   \"isDisposable\": false,   \"isValid\": true } ``` 
         * @summary 🌐 Quick check email
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quickCheck(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseMapStringObject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quickCheck(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailVerificationApi.quickCheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EmailVerificationApi - factory interface
 */
export const EmailVerificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmailVerificationApiFp(configuration)
    return {
        /**
         * Check đầy đủ bao gồm SMTP verification. Chậm, dùng cẩn thận!
         * @summary Xác thực email sâu (SMTP)
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deepVerify(email: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseMapStringObject> {
            return localVarFp.deepVerify(email, options).then((request) => request(axios, basePath));
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Xác thực email đầy đủ: Format + Disposable + MX records.  **3 Levels Check:** 1. ✅ Format validation (RFC 5322) 2. ✅ Disposable email check (block tempmail) 3. ✅ MX records check (domain có thể nhận email)  **Speed:** 50-200ms (DNS query)  **Use Case:** - Verify email trước khi register - Ensure email có thể nhận mail - Block fake domains  **Examples:** - ✅ test@gmail.com → Valid (has MX records) - ❌ test@tempmail.com → Invalid (disposable) - ❌ test@fakefake123.com → Invalid (no MX records)  **Response:** ```json {   \"email\": \"test@gmail.com\",   \"validFormat\": true,   \"isDisposable\": false,   \"hasMXRecords\": true,   \"mxRecords\": [\"gmail-smtp-in.l.google.com\"],   \"isValid\": true,   \"reason\": \"Email hợp lệ và có thể nhận email\" } ``` 
         * @summary 🌐 Full email verification
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fullVerify(email: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseMapStringObject> {
            return localVarFp.fullVerify(email, options).then((request) => request(axios, basePath));
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Kiểm tra nhanh email format và disposable email.  **Checks:** - ✅ Format validation (RFC 5322) - ✅ Disposable email check (tempmail, guerrillamail, etc.)  **Speed:** < 1ms (very fast)  **Use Case:** - Frontend real-time validation - Check email trước khi đăng ký - Block disposable emails  **Response:** ```json {   \"email\": \"test@gmail.com\",   \"validFormat\": true,   \"isDisposable\": false,   \"isValid\": true } ``` 
         * @summary 🌐 Quick check email
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quickCheck(email: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseMapStringObject> {
            return localVarFp.quickCheck(email, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EmailVerificationApi - object-oriented interface
 */
export class EmailVerificationApi extends BaseAPI {
    /**
     * Check đầy đủ bao gồm SMTP verification. Chậm, dùng cẩn thận!
     * @summary Xác thực email sâu (SMTP)
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deepVerify(email: string, options?: RawAxiosRequestConfig) {
        return EmailVerificationApiFp(this.configuration).deepVerify(email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * **Access:** 🌐 Public - Không cần authentication  Xác thực email đầy đủ: Format + Disposable + MX records.  **3 Levels Check:** 1. ✅ Format validation (RFC 5322) 2. ✅ Disposable email check (block tempmail) 3. ✅ MX records check (domain có thể nhận email)  **Speed:** 50-200ms (DNS query)  **Use Case:** - Verify email trước khi register - Ensure email có thể nhận mail - Block fake domains  **Examples:** - ✅ test@gmail.com → Valid (has MX records) - ❌ test@tempmail.com → Invalid (disposable) - ❌ test@fakefake123.com → Invalid (no MX records)  **Response:** ```json {   \"email\": \"test@gmail.com\",   \"validFormat\": true,   \"isDisposable\": false,   \"hasMXRecords\": true,   \"mxRecords\": [\"gmail-smtp-in.l.google.com\"],   \"isValid\": true,   \"reason\": \"Email hợp lệ và có thể nhận email\" } ``` 
     * @summary 🌐 Full email verification
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fullVerify(email: string, options?: RawAxiosRequestConfig) {
        return EmailVerificationApiFp(this.configuration).fullVerify(email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * **Access:** 🌐 Public - Không cần authentication  Kiểm tra nhanh email format và disposable email.  **Checks:** - ✅ Format validation (RFC 5322) - ✅ Disposable email check (tempmail, guerrillamail, etc.)  **Speed:** < 1ms (very fast)  **Use Case:** - Frontend real-time validation - Check email trước khi đăng ký - Block disposable emails  **Response:** ```json {   \"email\": \"test@gmail.com\",   \"validFormat\": true,   \"isDisposable\": false,   \"isValid\": true } ``` 
     * @summary 🌐 Quick check email
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quickCheck(email: string, options?: RawAxiosRequestConfig) {
        return EmailVerificationApiFp(this.configuration).quickCheck(email, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * NotificationsApi - axios parameter creator
 */
export const NotificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Đếm số thông báo chưa đọc
         * @summary Đếm thông báo chưa đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countUnread: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/notifications/unread/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Tạo thông báo cho user (Admin/Staff only)
         * @summary Tạo thông báo mới
         * @param {NotificationRequest} notificationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNotification: async (notificationRequest: NotificationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'notificationRequest' is not null or undefined
            assertParamExists('createNotification', 'notificationRequest', notificationRequest)
            const localVarPath = `/api/notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(notificationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Xóa thông báo
         * @summary Xóa thông báo
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteNotification: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteNotification', 'id', id)
            const localVarPath = `/api/notifications/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lấy tất cả thông báo trong hệ thống (Admin/Staff/Manager)
         * @summary Lấy tất cả thông báo
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllNotifications: async (page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lấy tất cả thông báo của user hiện tại
         * @summary Lấy thông báo của tôi
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyNotifications: async (page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/notifications/my`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lấy tất cả thông báo chưa đọc của user hiện tại
         * @summary Lấy thông báo chưa đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUnreadNotifications: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/notifications/unread`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lấy thông báo của một user cụ thể (Admin/Staff/Manager)
         * @summary Lấy thông báo của user
         * @param {number} userId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserNotificationsById: async (userId: number, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserNotificationsById', 'userId', userId)
            const localVarPath = `/api/notifications/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Đánh dấu tất cả thông báo đã đọc
         * @summary Đánh dấu tất cả đã đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAllAsRead: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/notifications/read-all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Đánh dấu thông báo đã đọc
         * @summary Đánh dấu đã đọc
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAsRead: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('markAsRead', 'id', id)
            const localVarPath = `/api/notifications/{id}/read`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gửi thông báo cho nhiều user (Admin only)
         * @summary Gửi thông báo hàng loạt
         * @param {Array<number>} userIds 
         * @param {string} title 
         * @param {string} message 
         * @param {SendBulkNotificationsTypeEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendBulkNotifications: async (userIds: Array<number>, title: string, message: string, type: SendBulkNotificationsTypeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userIds' is not null or undefined
            assertParamExists('sendBulkNotifications', 'userIds', userIds)
            // verify required parameter 'title' is not null or undefined
            assertParamExists('sendBulkNotifications', 'title', title)
            // verify required parameter 'message' is not null or undefined
            assertParamExists('sendBulkNotifications', 'message', message)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('sendBulkNotifications', 'type', type)
            const localVarPath = `/api/notifications/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (userIds) {
                localVarQueryParameter['userIds'] = userIds;
            }

            if (title !== undefined) {
                localVarQueryParameter['title'] = title;
            }

            if (message !== undefined) {
                localVarQueryParameter['message'] = message;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationsApi - functional programming interface
 */
export const NotificationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationsApiAxiosParamCreator(configuration)
    return {
        /**
         * Đếm số thông báo chưa đọc
         * @summary Đếm thông báo chưa đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async countUnread(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.countUnread(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.countUnread']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Tạo thông báo cho user (Admin/Staff only)
         * @summary Tạo thông báo mới
         * @param {NotificationRequest} notificationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNotification(notificationRequest: NotificationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseNotificationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNotification(notificationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.createNotification']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Xóa thông báo
         * @summary Xóa thông báo
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteNotification(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteNotification(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.deleteNotification']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lấy tất cả thông báo trong hệ thống (Admin/Staff/Manager)
         * @summary Lấy tất cả thông báo
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllNotifications(page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageNotificationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllNotifications(page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.getAllNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lấy tất cả thông báo của user hiện tại
         * @summary Lấy thông báo của tôi
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyNotifications(page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageNotificationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyNotifications(page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.getMyNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lấy tất cả thông báo chưa đọc của user hiện tại
         * @summary Lấy thông báo chưa đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUnreadNotifications(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListNotificationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUnreadNotifications(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.getUnreadNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lấy thông báo của một user cụ thể (Admin/Staff/Manager)
         * @summary Lấy thông báo của user
         * @param {number} userId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserNotificationsById(userId: number, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageNotificationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserNotificationsById(userId, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.getUserNotificationsById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Đánh dấu tất cả thông báo đã đọc
         * @summary Đánh dấu tất cả đã đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markAllAsRead(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markAllAsRead(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.markAllAsRead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Đánh dấu thông báo đã đọc
         * @summary Đánh dấu đã đọc
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markAsRead(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseNotificationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markAsRead(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.markAsRead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gửi thông báo cho nhiều user (Admin only)
         * @summary Gửi thông báo hàng loạt
         * @param {Array<number>} userIds 
         * @param {string} title 
         * @param {string} message 
         * @param {SendBulkNotificationsTypeEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendBulkNotifications(userIds: Array<number>, title: string, message: string, type: SendBulkNotificationsTypeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendBulkNotifications(userIds, title, message, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.sendBulkNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NotificationsApi - factory interface
 */
export const NotificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationsApiFp(configuration)
    return {
        /**
         * Đếm số thông báo chưa đọc
         * @summary Đếm thông báo chưa đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countUnread(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseLong> {
            return localVarFp.countUnread(options).then((request) => request(axios, basePath));
        },
        /**
         * Tạo thông báo cho user (Admin/Staff only)
         * @summary Tạo thông báo mới
         * @param {NotificationRequest} notificationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNotification(notificationRequest: NotificationRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseNotificationResponse> {
            return localVarFp.createNotification(notificationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Xóa thông báo
         * @summary Xóa thông báo
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteNotification(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.deleteNotification(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Lấy tất cả thông báo trong hệ thống (Admin/Staff/Manager)
         * @summary Lấy tất cả thông báo
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllNotifications(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageNotificationResponse> {
            return localVarFp.getAllNotifications(page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Lấy tất cả thông báo của user hiện tại
         * @summary Lấy thông báo của tôi
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyNotifications(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageNotificationResponse> {
            return localVarFp.getMyNotifications(page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Lấy tất cả thông báo chưa đọc của user hiện tại
         * @summary Lấy thông báo chưa đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUnreadNotifications(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListNotificationResponse> {
            return localVarFp.getUnreadNotifications(options).then((request) => request(axios, basePath));
        },
        /**
         * Lấy thông báo của một user cụ thể (Admin/Staff/Manager)
         * @summary Lấy thông báo của user
         * @param {number} userId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserNotificationsById(userId: number, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageNotificationResponse> {
            return localVarFp.getUserNotificationsById(userId, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Đánh dấu tất cả thông báo đã đọc
         * @summary Đánh dấu tất cả đã đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAllAsRead(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.markAllAsRead(options).then((request) => request(axios, basePath));
        },
        /**
         * Đánh dấu thông báo đã đọc
         * @summary Đánh dấu đã đọc
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAsRead(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseNotificationResponse> {
            return localVarFp.markAsRead(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Gửi thông báo cho nhiều user (Admin only)
         * @summary Gửi thông báo hàng loạt
         * @param {Array<number>} userIds 
         * @param {string} title 
         * @param {string} message 
         * @param {SendBulkNotificationsTypeEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendBulkNotifications(userIds: Array<number>, title: string, message: string, type: SendBulkNotificationsTypeEnum, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.sendBulkNotifications(userIds, title, message, type, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationsApi - object-oriented interface
 */
export class NotificationsApi extends BaseAPI {
    /**
     * Đếm số thông báo chưa đọc
     * @summary Đếm thông báo chưa đọc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public countUnread(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).countUnread(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Tạo thông báo cho user (Admin/Staff only)
     * @summary Tạo thông báo mới
     * @param {NotificationRequest} notificationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createNotification(notificationRequest: NotificationRequest, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).createNotification(notificationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Xóa thông báo
     * @summary Xóa thông báo
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteNotification(id: number, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).deleteNotification(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lấy tất cả thông báo trong hệ thống (Admin/Staff/Manager)
     * @summary Lấy tất cả thông báo
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllNotifications(page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).getAllNotifications(page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lấy tất cả thông báo của user hiện tại
     * @summary Lấy thông báo của tôi
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMyNotifications(page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).getMyNotifications(page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lấy tất cả thông báo chưa đọc của user hiện tại
     * @summary Lấy thông báo chưa đọc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUnreadNotifications(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).getUnreadNotifications(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lấy thông báo của một user cụ thể (Admin/Staff/Manager)
     * @summary Lấy thông báo của user
     * @param {number} userId 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserNotificationsById(userId: number, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).getUserNotificationsById(userId, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Đánh dấu tất cả thông báo đã đọc
     * @summary Đánh dấu tất cả đã đọc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public markAllAsRead(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).markAllAsRead(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Đánh dấu thông báo đã đọc
     * @summary Đánh dấu đã đọc
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public markAsRead(id: number, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).markAsRead(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gửi thông báo cho nhiều user (Admin only)
     * @summary Gửi thông báo hàng loạt
     * @param {Array<number>} userIds 
     * @param {string} title 
     * @param {string} message 
     * @param {SendBulkNotificationsTypeEnum} type 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendBulkNotifications(userIds: Array<number>, title: string, message: string, type: SendBulkNotificationsTypeEnum, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).sendBulkNotifications(userIds, title, message, type, options).then((request) => request(this.axios, this.basePath));
    }
}

export const SendBulkNotificationsTypeEnum = {
    OrderCreated: 'ORDER_CREATED',
    OrderConfirmed: 'ORDER_CONFIRMED',
    OrderProcessing: 'ORDER_PROCESSING',
    OrderReady: 'ORDER_READY',
    OrderDelivering: 'ORDER_DELIVERING',
    OrderCompleted: 'ORDER_COMPLETED',
    OrderCancelled: 'ORDER_CANCELLED',
    PaymentSuccess: 'PAYMENT_SUCCESS',
    PaymentFailed: 'PAYMENT_FAILED',
    Promotion: 'PROMOTION',
    System: 'SYSTEM',
    Other: 'OTHER'
} as const;
export type SendBulkNotificationsTypeEnum = typeof SendBulkNotificationsTypeEnum[keyof typeof SendBulkNotificationsTypeEnum];


/**
 * PasswordManagementApi - axios parameter creator
 */
export const PasswordManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * **Access:** 🌐 Public - Không cần authentication (verify qua token)  Xác nhận bật/tắt 2FA cho password change.  **Flow:** 1. User request toggle 2FA (authenticated endpoint) 2. System tạo token + send email 3. User click link trong email 4. Call API này để confirm 5. 2FA setting được cập nhật  **After Enable 2FA:** - User đổi password → Phải xác nhận qua email - Tăng bảo mật  **After Disable 2FA:** - User đổi password → Đổi ngay (chỉ cần old password) - Tiện lợi hơn  **Response:** - Success: Cập nhật 2FA setting thành công - Error: Token invalid/expired 
         * @summary 🌐 Xác nhận toggle 2FA
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirm2FAToggle: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('confirm2FAToggle', 'token', token)
            const localVarPath = `/api/auth/security/2fa-toggle/confirm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Gửi email reset password cho user quên mật khẩu.  **Email Verification:** - Check format email - Check disposable email (block) - Check MX records (domain tồn tại)  **Flow:** 1. User nhập email 2. System verify email 3. Tạo token (30 phút) 4. Gửi email với link reset  **Security:** - Không tiết lộ email có tồn tại hay không - Luôn return success message - Token one-time use  **Response:** - Success message (dù email có tồn tại hay không) 
         * @summary 🌐 Quên mật khẩu (Bước 1)
         * @param {ForgotPasswordRequest} forgotPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPassword: async (forgotPasswordRequest: ForgotPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'forgotPasswordRequest' is not null or undefined
            assertParamExists('forgotPassword', 'forgotPasswordRequest', forgotPasswordRequest)
            const localVarPath = `/api/auth/forgot-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(forgotPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Reset password với token từ email.  **Flow:** 1. User nhập password mới + confirm 2. System validate token 3. Check password match 4. Update password (BCrypt hash) 5. Mark token as used 6. User có thể đăng nhập với password mới  **Validations:** - Token valid (chưa hết hạn, chưa dùng) - Password >= 8 ký tự - Password match confirm password  **Security:** - Token one-time use - Password hashed with BCrypt - Old tokens deleted after success  **Response:** - Success: Đổi password thành công - Error: Token invalid hoặc passwords không match 
         * @summary 🌐 Reset mật khẩu (Bước 3)
         * @param {ResetPasswordRequest} resetPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetPassword: async (resetPasswordRequest: ResetPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resetPasswordRequest' is not null or undefined
            assertParamExists('resetPassword', 'resetPasswordRequest', resetPasswordRequest)
            const localVarPath = `/api/auth/reset-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(resetPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Kiểm tra token reset password còn hợp lệ không.  **Use Case:** - Frontend check token khi user click link trong email - Hiển thị form reset password nếu valid - Hiển thị error nếu expired/invalid  **Validations:** - Token tồn tại trong DB - Token chưa hết hạn (30 phút) - Token chưa được sử dụng  **Response:** - true: Token hợp lệ, cho phép reset - false: Token expired/invalid 
         * @summary 🌐 Validate token reset (Bước 2)
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateResetToken: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('validateResetToken', 'token', token)
            const localVarPath = `/api/auth/reset-password/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Validate token để bật/tắt 2FA setting.  **Context:** - User request bật/tắt 2FA cho password change - System gửi email xác nhận - User click link trong email - Frontend call API này để validate  **What is 2FA for Password Change?** - Khi BẬT: Đổi password phải xác nhận qua email - Khi TẮT: Đổi password ngay lập tức (chỉ cần password cũ)  **Response:** - Success: Token valid - Error: Token expired/invalid 
         * @summary 🌐 Validate token toggle 2FA
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateToken: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('validateToken', 'token', token)
            const localVarPath = `/api/auth/security/2fa-toggle/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PasswordManagementApi - functional programming interface
 */
export const PasswordManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PasswordManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * **Access:** 🌐 Public - Không cần authentication (verify qua token)  Xác nhận bật/tắt 2FA cho password change.  **Flow:** 1. User request toggle 2FA (authenticated endpoint) 2. System tạo token + send email 3. User click link trong email 4. Call API này để confirm 5. 2FA setting được cập nhật  **After Enable 2FA:** - User đổi password → Phải xác nhận qua email - Tăng bảo mật  **After Disable 2FA:** - User đổi password → Đổi ngay (chỉ cần old password) - Tiện lợi hơn  **Response:** - Success: Cập nhật 2FA setting thành công - Error: Token invalid/expired 
         * @summary 🌐 Xác nhận toggle 2FA
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async confirm2FAToggle(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.confirm2FAToggle(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PasswordManagementApi.confirm2FAToggle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Gửi email reset password cho user quên mật khẩu.  **Email Verification:** - Check format email - Check disposable email (block) - Check MX records (domain tồn tại)  **Flow:** 1. User nhập email 2. System verify email 3. Tạo token (30 phút) 4. Gửi email với link reset  **Security:** - Không tiết lộ email có tồn tại hay không - Luôn return success message - Token one-time use  **Response:** - Success message (dù email có tồn tại hay không) 
         * @summary 🌐 Quên mật khẩu (Bước 1)
         * @param {ForgotPasswordRequest} forgotPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async forgotPassword(forgotPasswordRequest: ForgotPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.forgotPassword(forgotPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PasswordManagementApi.forgotPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Reset password với token từ email.  **Flow:** 1. User nhập password mới + confirm 2. System validate token 3. Check password match 4. Update password (BCrypt hash) 5. Mark token as used 6. User có thể đăng nhập với password mới  **Validations:** - Token valid (chưa hết hạn, chưa dùng) - Password >= 8 ký tự - Password match confirm password  **Security:** - Token one-time use - Password hashed with BCrypt - Old tokens deleted after success  **Response:** - Success: Đổi password thành công - Error: Token invalid hoặc passwords không match 
         * @summary 🌐 Reset mật khẩu (Bước 3)
         * @param {ResetPasswordRequest} resetPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resetPassword(resetPasswordRequest: ResetPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resetPassword(resetPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PasswordManagementApi.resetPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Kiểm tra token reset password còn hợp lệ không.  **Use Case:** - Frontend check token khi user click link trong email - Hiển thị form reset password nếu valid - Hiển thị error nếu expired/invalid  **Validations:** - Token tồn tại trong DB - Token chưa hết hạn (30 phút) - Token chưa được sử dụng  **Response:** - true: Token hợp lệ, cho phép reset - false: Token expired/invalid 
         * @summary 🌐 Validate token reset (Bước 2)
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateResetToken(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateResetToken(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PasswordManagementApi.validateResetToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Validate token để bật/tắt 2FA setting.  **Context:** - User request bật/tắt 2FA cho password change - System gửi email xác nhận - User click link trong email - Frontend call API này để validate  **What is 2FA for Password Change?** - Khi BẬT: Đổi password phải xác nhận qua email - Khi TẮT: Đổi password ngay lập tức (chỉ cần password cũ)  **Response:** - Success: Token valid - Error: Token expired/invalid 
         * @summary 🌐 Validate token toggle 2FA
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateToken(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateToken(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PasswordManagementApi.validateToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PasswordManagementApi - factory interface
 */
export const PasswordManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PasswordManagementApiFp(configuration)
    return {
        /**
         * **Access:** 🌐 Public - Không cần authentication (verify qua token)  Xác nhận bật/tắt 2FA cho password change.  **Flow:** 1. User request toggle 2FA (authenticated endpoint) 2. System tạo token + send email 3. User click link trong email 4. Call API này để confirm 5. 2FA setting được cập nhật  **After Enable 2FA:** - User đổi password → Phải xác nhận qua email - Tăng bảo mật  **After Disable 2FA:** - User đổi password → Đổi ngay (chỉ cần old password) - Tiện lợi hơn  **Response:** - Success: Cập nhật 2FA setting thành công - Error: Token invalid/expired 
         * @summary 🌐 Xác nhận toggle 2FA
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirm2FAToggle(token: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.confirm2FAToggle(token, options).then((request) => request(axios, basePath));
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Gửi email reset password cho user quên mật khẩu.  **Email Verification:** - Check format email - Check disposable email (block) - Check MX records (domain tồn tại)  **Flow:** 1. User nhập email 2. System verify email 3. Tạo token (30 phút) 4. Gửi email với link reset  **Security:** - Không tiết lộ email có tồn tại hay không - Luôn return success message - Token one-time use  **Response:** - Success message (dù email có tồn tại hay không) 
         * @summary 🌐 Quên mật khẩu (Bước 1)
         * @param {ForgotPasswordRequest} forgotPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPassword(forgotPasswordRequest: ForgotPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.forgotPassword(forgotPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Reset password với token từ email.  **Flow:** 1. User nhập password mới + confirm 2. System validate token 3. Check password match 4. Update password (BCrypt hash) 5. Mark token as used 6. User có thể đăng nhập với password mới  **Validations:** - Token valid (chưa hết hạn, chưa dùng) - Password >= 8 ký tự - Password match confirm password  **Security:** - Token one-time use - Password hashed with BCrypt - Old tokens deleted after success  **Response:** - Success: Đổi password thành công - Error: Token invalid hoặc passwords không match 
         * @summary 🌐 Reset mật khẩu (Bước 3)
         * @param {ResetPasswordRequest} resetPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetPassword(resetPasswordRequest: ResetPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.resetPassword(resetPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Kiểm tra token reset password còn hợp lệ không.  **Use Case:** - Frontend check token khi user click link trong email - Hiển thị form reset password nếu valid - Hiển thị error nếu expired/invalid  **Validations:** - Token tồn tại trong DB - Token chưa hết hạn (30 phút) - Token chưa được sử dụng  **Response:** - true: Token hợp lệ, cho phép reset - false: Token expired/invalid 
         * @summary 🌐 Validate token reset (Bước 2)
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateResetToken(token: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseBoolean> {
            return localVarFp.validateResetToken(token, options).then((request) => request(axios, basePath));
        },
        /**
         * **Access:** 🌐 Public - Không cần authentication  Validate token để bật/tắt 2FA setting.  **Context:** - User request bật/tắt 2FA cho password change - System gửi email xác nhận - User click link trong email - Frontend call API này để validate  **What is 2FA for Password Change?** - Khi BẬT: Đổi password phải xác nhận qua email - Khi TẮT: Đổi password ngay lập tức (chỉ cần password cũ)  **Response:** - Success: Token valid - Error: Token expired/invalid 
         * @summary 🌐 Validate token toggle 2FA
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateToken(token: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.validateToken(token, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PasswordManagementApi - object-oriented interface
 */
export class PasswordManagementApi extends BaseAPI {
    /**
     * **Access:** 🌐 Public - Không cần authentication (verify qua token)  Xác nhận bật/tắt 2FA cho password change.  **Flow:** 1. User request toggle 2FA (authenticated endpoint) 2. System tạo token + send email 3. User click link trong email 4. Call API này để confirm 5. 2FA setting được cập nhật  **After Enable 2FA:** - User đổi password → Phải xác nhận qua email - Tăng bảo mật  **After Disable 2FA:** - User đổi password → Đổi ngay (chỉ cần old password) - Tiện lợi hơn  **Response:** - Success: Cập nhật 2FA setting thành công - Error: Token invalid/expired 
     * @summary 🌐 Xác nhận toggle 2FA
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public confirm2FAToggle(token: string, options?: RawAxiosRequestConfig) {
        return PasswordManagementApiFp(this.configuration).confirm2FAToggle(token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * **Access:** 🌐 Public - Không cần authentication  Gửi email reset password cho user quên mật khẩu.  **Email Verification:** - Check format email - Check disposable email (block) - Check MX records (domain tồn tại)  **Flow:** 1. User nhập email 2. System verify email 3. Tạo token (30 phút) 4. Gửi email với link reset  **Security:** - Không tiết lộ email có tồn tại hay không - Luôn return success message - Token one-time use  **Response:** - Success message (dù email có tồn tại hay không) 
     * @summary 🌐 Quên mật khẩu (Bước 1)
     * @param {ForgotPasswordRequest} forgotPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public forgotPassword(forgotPasswordRequest: ForgotPasswordRequest, options?: RawAxiosRequestConfig) {
        return PasswordManagementApiFp(this.configuration).forgotPassword(forgotPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * **Access:** 🌐 Public - Không cần authentication  Reset password với token từ email.  **Flow:** 1. User nhập password mới + confirm 2. System validate token 3. Check password match 4. Update password (BCrypt hash) 5. Mark token as used 6. User có thể đăng nhập với password mới  **Validations:** - Token valid (chưa hết hạn, chưa dùng) - Password >= 8 ký tự - Password match confirm password  **Security:** - Token one-time use - Password hashed with BCrypt - Old tokens deleted after success  **Response:** - Success: Đổi password thành công - Error: Token invalid hoặc passwords không match 
     * @summary 🌐 Reset mật khẩu (Bước 3)
     * @param {ResetPasswordRequest} resetPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public resetPassword(resetPasswordRequest: ResetPasswordRequest, options?: RawAxiosRequestConfig) {
        return PasswordManagementApiFp(this.configuration).resetPassword(resetPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * **Access:** 🌐 Public - Không cần authentication  Kiểm tra token reset password còn hợp lệ không.  **Use Case:** - Frontend check token khi user click link trong email - Hiển thị form reset password nếu valid - Hiển thị error nếu expired/invalid  **Validations:** - Token tồn tại trong DB - Token chưa hết hạn (30 phút) - Token chưa được sử dụng  **Response:** - true: Token hợp lệ, cho phép reset - false: Token expired/invalid 
     * @summary 🌐 Validate token reset (Bước 2)
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public validateResetToken(token: string, options?: RawAxiosRequestConfig) {
        return PasswordManagementApiFp(this.configuration).validateResetToken(token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * **Access:** 🌐 Public - Không cần authentication  Validate token để bật/tắt 2FA setting.  **Context:** - User request bật/tắt 2FA cho password change - System gửi email xác nhận - User click link trong email - Frontend call API này để validate  **What is 2FA for Password Change?** - Khi BẬT: Đổi password phải xác nhận qua email - Khi TẮT: Đổi password ngay lập tức (chỉ cần password cũ)  **Response:** - Success: Token valid - Error: Token expired/invalid 
     * @summary 🌐 Validate token toggle 2FA
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public validateToken(token: string, options?: RawAxiosRequestConfig) {
        return PasswordManagementApiFp(this.configuration).validateToken(token, options).then((request) => request(this.axios, this.basePath));
    }
}



